import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DB_PATH = path.join(__dirname, 'data', 'db.json');
const PUBLIC_DIR = path.join(__dirname, 'public');
const PORT = Number(process.env.PORT || 5173);
const SECRET = process.env.JWT_SECRET || 'via-facil-dev-secret-change-in-production';

const now = () => new Date().toISOString();
const id = (prefix) => `${prefix}_${crypto.randomUUID()}`;
const cleanUser = ({ passwordHash, salt, ...user }) => user;
const json = (res, status, data) => {res.writeHead(status, {'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
const mime = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon'};

async function readDb(){const db=JSON.parse(await fs.readFile(DB_PATH,'utf8'));for(const key of ['users','rides','bookings','deliveries','messages','reviews'])db[key]??=[];return db;}
async function writeDb(db){await fs.writeFile(DB_PATH,JSON.stringify(db,null,2));}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(password,salt,64).toString('hex');return {salt,passwordHash:hash};}
function verifyPassword(password,user){return crypto.timingSafeEqual(Buffer.from(hashPassword(password,user.salt).passwordHash,'hex'),Buffer.from(user.passwordHash,'hex'));}
function sign(payload){const body=Buffer.from(JSON.stringify({...payload,exp:Date.now()+7*86400000})).toString('base64url');const sig=crypto.createHmac('sha256',SECRET).update(body).digest('base64url');return `${body}.${sig}`;}
function verify(token){const [body,sig]=String(token||'').split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',SECRET).update(body).digest('base64url');if(sig!==expected)return null;const payload=JSON.parse(Buffer.from(body,'base64url').toString());return payload.exp>Date.now()?payload:null;}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>1e6)throw new Error('Payload muito grande');}return raw?JSON.parse(raw):{};}
function auth(req){return verify(req.headers.authorization?.replace(/^Bearer\s+/i,''));}
function stopsFor(ride){return Array.isArray(ride.stops)&&ride.stops.length>1?ride.stops:[ride.origin,ride.destination];}
function segmentOnRide(ride,pickup,dropoff){const stops=stopsFor(ride).map(s=>s.toLocaleLowerCase('pt-BR'));const from=stops.indexOf(String(pickup||'').trim().toLocaleLowerCase('pt-BR'));const to=stops.indexOf(String(dropoff||'').trim().toLocaleLowerCase('pt-BR'));return from>=0&&to>from;}

async function seed(){const db=await readDb();if(db.users.length)return;const adminId=id('usr'),driverId=id('usr');const a=hashPassword('admin123'),d=hashPassword('motorista123');db.users.push({id:adminId,name:'Administrador Via Fácil',email:'admin@viafacil.com',phone:'(00) 90000-0000',role:'admin',rating:5,verified:true,...a,createdAt:now()},{id:driverId,name:'Carlos Motorista',email:'motorista@viafacil.com',phone:'(00) 98888-0000',role:'driver',rating:4.9,verified:true,vehicle:'Chevrolet Onix • ABC1D23',...d,createdAt:now()});const date=(n)=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);db.rides.push({id:id('ride'),driverId,origin:'Centro',destination:'Aeroporto',date:date(1),time:'08:00',seats:3,availableSeats:3,price:28,vehicle:'Chevrolet Onix',notes:'Uma parada rápida no caminho.',status:'active',createdAt:now()},{id:id('ride'),driverId,origin:'Rodoviária',destination:'Centro',date:date(2),time:'17:30',seats:4,availableSeats:4,price:18,vehicle:'Chevrolet Onix',notes:'Bagagem pequena permitida.',status:'active',createdAt:now()});await writeDb(db);}

async function api(req,res,url){
  const user=auth(req);const db=await readDb();const method=req.method;
  if(method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,app:'Via Fácil'});
  if(method==='POST'&&url.pathname==='/api/auth/register'){const data=await body(req);if(!data.name||!data.email||!data.password)return json(res,400,{error:'Nome, e-mail e senha são obrigatórios.'});if(db.users.some(u=>u.email.toLowerCase()===data.email.toLowerCase()))return json(res,409,{error:'Este e-mail já está cadastrado.'});const pass=hashPassword(data.password);const newUser={id:id('usr'),name:data.name.trim(),email:data.email.trim().toLowerCase(),phone:data.phone?.trim()||'',role:['passenger','driver'].includes(data.role)?data.role:'passenger',rating:5,verified:false,...pass,createdAt:now()};db.users.push(newUser);await writeDb(db);return json(res,201,{token:sign({id:newUser.id,role:newUser.role,name:newUser.name}),user:cleanUser(newUser)});}
  if(method==='POST'&&url.pathname==='/api/auth/login'){const data=await body(req);const found=db.users.find(u=>u.email.toLowerCase()===String(data.email||'').toLowerCase());if(!found||!verifyPassword(data.password||'',found))return json(res,401,{error:'E-mail ou senha incorretos.'});return json(res,200,{token:sign({id:found.id,role:found.role,name:found.name}),user:cleanUser(found)});}
  if(method==='GET'&&url.pathname==='/api/rides'){const origin=url.searchParams.get('origin')||'',destination=url.searchParams.get('destination')||'',date=url.searchParams.get('date')||'';const rides=db.rides.filter(r=>r.status==='active').filter(r=>{if(!origin&&!destination)return true;const stops=stopsFor(r).map(s=>s.toLowerCase());const from=origin?stops.findIndex(s=>s.includes(origin.toLowerCase())):0;const to=destination?stops.findIndex((s,i)=>i>from&&s.includes(destination.toLowerCase())):stops.length-1;return from>=0&&to>from;}).filter(r=>!date||r.date===date).map(r=>({...r,stops:stopsFor(r),acceptsPassengers:r.acceptsPassengers!==false,acceptsDeliveries:r.acceptsDeliveries===true,driver:cleanUser(db.users.find(u=>u.id===r.driverId)||{})})).sort((a,b)=>`${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`));return json(res,200,{rides});}
  if(!user)return json(res,401,{error:'Faça login para continuar.'});
  if(method==='GET'&&url.pathname==='/api/me'){const found=db.users.find(u=>u.id===user.id);return json(res,200,{user:cleanUser(found)});}
  if(method==='POST'&&url.pathname==='/api/rides'){const data=await body(req);const stops=[data.origin,...(Array.isArray(data.intermediateStops)?data.intermediateStops:[]),data.destination].map(s=>String(s||'').trim()).filter(Boolean);if(stops.length<2||!data.date||!data.time||!data.seats||data.price===undefined)return json(res,400,{error:'Preencha todos os campos obrigatórios.'});if(new Set(stops.map(s=>s.toLowerCase())).size!==stops.length)return json(res,400,{error:'Cada parada do percurso deve ser diferente.'});const ride={id:id('ride'),driverId:user.id,origin:stops[0],destination:stops.at(-1),stops,date:data.date,time:data.time,seats:Number(data.seats),availableSeats:Number(data.seats),price:Number(data.price),deliveryPrice:Number(data.deliveryPrice||0),acceptsPassengers:data.acceptsPassengers!==false,acceptsDeliveries:data.acceptsDeliveries===true,vehicle:data.vehicle||'Veículo não informado',notes:data.notes||'',status:'active',createdAt:now()};if(!ride.acceptsPassengers&&!ride.acceptsDeliveries)return json(res,400,{error:'Selecione passageiros, entregas ou ambos.'});db.rides.push(ride);await writeDb(db);return json(res,201,{ride});}
  const bookMatch=url.pathname.match(/^\/api\/rides\/([^/]+)\/book$/);if(method==='POST'&&bookMatch){const data=await body(req),seats=Number(data.seats||1),ride=db.rides.find(r=>r.id===bookMatch[1]);if(!ride||ride.status!=='active')return json(res,404,{error:'Carona não encontrada.'});if(ride.acceptsPassengers===false)return json(res,400,{error:'Este percurso aceita somente entregas.'});if(ride.driverId===user.id)return json(res,400,{error:'Você não pode reservar sua própria carona.'});if(!segmentOnRide(ride,data.pickup,data.dropoff))return json(res,400,{error:'Selecione um trecho válido na ordem do percurso.'});if(seats<1||seats>ride.availableSeats)return json(res,400,{error:'Quantidade de vagas indisponível.'});const booking={id:id('book'),rideId:ride.id,passengerId:user.id,pickup:data.pickup,dropoff:data.dropoff,seats,total:seats*ride.price,status:'pending',createdAt:now()};db.bookings.push(booking);await writeDb(db);return json(res,201,{booking});}
  if(method==='GET'&&url.pathname==='/api/my/bookings')return json(res,200,{bookings:db.bookings.filter(b=>b.passengerId===user.id).map(b=>({...b,ride:db.rides.find(r=>r.id===b.rideId)}))});
  if(method==='GET'&&url.pathname==='/api/my/ride-requests')return json(res,200,{bookings:db.bookings.filter(b=>db.rides.find(r=>r.id===b.rideId)?.driverId===user.id).map(b=>({...b,ride:db.rides.find(r=>r.id===b.rideId),passenger:cleanUser(db.users.find(u=>u.id===b.passengerId)||{})}))});
  const respondMatch=url.pathname.match(/^\/api\/bookings\/([^/]+)\/respond$/);if(method==='PATCH'&&respondMatch){const data=await body(req),booking=db.bookings.find(b=>b.id===respondMatch[1]),ride=booking&&db.rides.find(r=>r.id===booking.rideId);if(!booking||!ride||ride.driverId!==user.id)return json(res,404,{error:'Solicitação não encontrada.'});if(booking.status!=='pending')return json(res,400,{error:'Esta solicitação já foi respondida.'});if(data.action==='accept'){if(booking.seats>ride.availableSeats)return json(res,400,{error:'Não há mais vagas suficientes.'});booking.status='confirmed';ride.availableSeats-=booking.seats;}else if(data.action==='reject')booking.status='rejected';else return json(res,400,{error:'Ação inválida.'});booking.respondedAt=now();await writeDb(db);return json(res,200,{booking});}
  const cancelMatch=url.pathname.match(/^\/api\/bookings\/([^/]+)\/cancel$/);if(method==='PATCH'&&cancelMatch){const booking=db.bookings.find(b=>b.id===cancelMatch[1]&&b.passengerId===user.id);if(!booking)return json(res,404,{error:'Reserva não encontrada.'});if(!['cancelled','rejected'].includes(booking.status)){const wasConfirmed=booking.status==='confirmed';booking.status='cancelled';const ride=db.rides.find(r=>r.id===booking.rideId);if(ride&&wasConfirmed)ride.availableSeats+=booking.seats;await writeDb(db);}return json(res,200,{booking});}
  if(method==='POST'&&url.pathname==='/api/deliveries'){const data=await body(req),ride=db.rides.find(r=>r.id===data.rideId);if(!ride||ride.status!=='active'||ride.acceptsDeliveries!==true)return json(res,400,{error:'Selecione um percurso que aceite entregas.'});if(ride.driverId===user.id)return json(res,400,{error:'Você não pode solicitar entrega na própria viagem.'});if(!segmentOnRide(ride,data.pickup,data.destination))return json(res,400,{error:'A coleta e a entrega precisam seguir a ordem do percurso.'});if(!data.packageType||!data.recipient)return json(res,400,{error:'Preencha todos os campos obrigatórios.'});const delivery={id:id('del'),rideId:ride.id,customerId:user.id,pickup:data.pickup,destination:data.destination,date:ride.date,time:ride.time,packageType:data.packageType,recipient:data.recipient,phone:data.phone||'',notes:data.notes||'',status:'requested',trackingCode:`VF${Math.random().toString(36).slice(2,8).toUpperCase()}`,createdAt:now()};db.deliveries.push(delivery);await writeDb(db);return json(res,201,{delivery});}
  if(method==='GET'&&url.pathname==='/api/my/deliveries')return json(res,200,{deliveries:db.deliveries.filter(d=>d.customerId===user.id)});
  const messageMatch=url.pathname.match(/^\/api\/rides\/([^/]+)\/messages$/);if(messageMatch&&(method==='GET'||method==='POST')){const ride=db.rides.find(r=>r.id===messageMatch[1]);if(!ride)return json(res,404,{error:'Carona não encontrada.'});const data=method==='POST'?await body(req):{};const participantId=ride.driverId===user.id?(url.searchParams.get('participantId')||data.recipientId):user.id;if(!participantId)return json(res,400,{error:'Informe o passageiro da conversa.'});if(method==='GET'){const messages=db.messages.filter(m=>m.rideId===ride.id&&m.participantId===participantId);return json(res,200,{messages,ride:{...ride,stops:stopsFor(ride)},participant:cleanUser(db.users.find(u=>u.id===participantId)||{})});}if(!String(data.text||'').trim())return json(res,400,{error:'Digite uma mensagem.'});const message={id:id('msg'),rideId:ride.id,participantId,senderId:user.id,text:String(data.text).trim().slice(0,1000),createdAt:now()};db.messages.push(message);await writeDb(db);return json(res,201,{message});}
  if(method==='GET'&&url.pathname==='/api/my/conversations'){const mine=db.messages.filter(m=>m.senderId===user.id||m.participantId===user.id);const keys=[...new Set(mine.map(m=>`${m.rideId}|${m.participantId}`))];const conversations=keys.map(key=>{const [rideId,participantId]=key.split('|'),items=mine.filter(m=>m.rideId===rideId&&m.participantId===participantId);return {ride:db.rides.find(r=>r.id===rideId),participant:cleanUser(db.users.find(u=>u.id===participantId)||{}),lastMessage:items.at(-1)};}).filter(c=>c.ride).sort((a,b)=>b.lastMessage.createdAt.localeCompare(a.lastMessage.createdAt));return json(res,200,{conversations});}
  if(method==='GET'&&url.pathname==='/api/admin/summary'){if(user.role!=='admin')return json(res,403,{error:'Acesso restrito ao administrador.'});return json(res,200,{users:db.users.length,rides:db.rides.length,bookings:db.bookings.length,deliveries:db.deliveries.length,revenue:db.bookings.filter(b=>b.status==='confirmed').reduce((s,b)=>s+b.total,0)});}
  return json(res,404,{error:'Rota não encontrada.'});
}

async function serve(req,res,url){let pathname=decodeURIComponent(url.pathname);if(pathname==='/')pathname='/index.html';let file=path.normalize(path.join(PUBLIC_DIR,pathname));if(!file.startsWith(PUBLIC_DIR))return json(res,403,{error:'Acesso negado.'});try{const data=await fs.readFile(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(data);}catch{const data=await fs.readFile(path.join(PUBLIC_DIR,'index.html'));res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(data);}}

await seed();
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'127.0.0.1'}`);if(url.pathname.startsWith('/api/'))await api(req,res,url);else await serve(req,res,url);}catch(err){console.error(err);json(res,500,{error:'Erro interno do servidor.'});}});
server.listen(PORT, '0.0.0.0', () => {
  console.log(`\nVIA FÁCIL disponível na porta ${PORT}\n`);
});
