import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';
import pg from 'pg';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DB_PATH = path.join(__dirname, 'data', 'db.json');
const PUBLIC_DIR = path.join(__dirname, 'public');
const LEAFLET_DIR = path.join(__dirname, 'node_modules', 'leaflet', 'dist');
const PORT = Number(process.env.PORT || 5173);
const IS_PRODUCTION = process.env.NODE_ENV === 'production';
const SECRET = process.env.JWT_SECRET || (IS_PRODUCTION ? '' : 'via-facil-dev-secret-change-in-production');
const DATABASE_URL = process.env.DATABASE_URL || '';
const GEOCODING_URL = process.env.GEOCODING_URL || 'https://nominatim.openstreetmap.org';
const ROUTING_URL = process.env.ROUTING_URL || 'https://router.project-osrm.org';
const MAP_CONTACT_EMAIL = process.env.MAP_CONTACT_EMAIL || '';
if(IS_PRODUCTION&&!SECRET)throw new Error('JWT_SECRET é obrigatório em produção.');
if(IS_PRODUCTION&&!DATABASE_URL)throw new Error('DATABASE_URL é obrigatório em produção.');
const pool=DATABASE_URL?new pg.Pool({connectionString:DATABASE_URL,max:Number(process.env.DATABASE_POOL_SIZE||5)}):null;
let databaseReady;

const now = () => new Date().toISOString();
const id = (prefix) => `${prefix}_${crypto.randomUUID()}`;
const cleanUser = ({ passwordHash, salt, ...user }) => user;
const publicUser = (user={},reviews=[]) => {const {id,name,role,rating,verified,profileTitle,bio,serviceArea,paymentMethods,paymentLink,profilePhoto,plan='free'}=user,received=reviews.filter(review=>review.driverId===id),average=received.length?received.reduce((sum,review)=>sum+review.rating,0)/received.length:Number(rating||5);return {id,name,role,rating:Number(average.toFixed(1)),reviewCount:received.length,verified,profileTitle:profileTitle||name,bio:bio||'',serviceArea:serviceArea||'',paymentMethods:Array.isArray(paymentMethods)?paymentMethods:[],paymentLink:paymentLink||'',profilePhoto:profilePhoto||'',plan};};
const json = (res, status, data) => {res.writeHead(status, {'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
const mime = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon'};

const emptyDb=()=>({users:[],rides:[],bookings:[],deliveries:[],messages:[],reviews:[]});
async function initDatabase(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS app_state (id SMALLINT PRIMARY KEY CHECK (id = 1), data JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await pool.query(`INSERT INTO app_state (id,data) VALUES (1,$1::jsonb) ON CONFLICT (id) DO NOTHING`,[JSON.stringify(emptyDb())]);}
async function readDb(){if(pool){databaseReady??=initDatabase();await databaseReady;const {rows}=await pool.query('SELECT data FROM app_state WHERE id = 1');const db=rows[0]?.data||emptyDb();for(const key of ['users','rides','bookings','deliveries','messages','reviews'])db[key]??=[];return db;}const db=JSON.parse(await fs.readFile(DB_PATH,'utf8'));for(const key of ['users','rides','bookings','deliveries','messages','reviews'])db[key]??=[];return db;}
let pendingWrite=Promise.resolve();
async function writeDb(db){if(pool){pendingWrite=pendingWrite.then(()=>pool.query('UPDATE app_state SET data=$1::jsonb, updated_at=NOW() WHERE id=1',[JSON.stringify(db)]));await pendingWrite;return;}await fs.writeFile(DB_PATH,JSON.stringify(db,null,2));}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(password,salt,64).toString('hex');return {salt,passwordHash:hash};}
function verifyPassword(password,user){return crypto.timingSafeEqual(Buffer.from(hashPassword(password,user.salt).passwordHash,'hex'),Buffer.from(user.passwordHash,'hex'));}
function sign(payload){const body=Buffer.from(JSON.stringify({...payload,exp:Date.now()+7*86400000})).toString('base64url');const sig=crypto.createHmac('sha256',SECRET).update(body).digest('base64url');return `${body}.${sig}`;}
function verify(token){const [body,sig]=String(token||'').split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',SECRET).update(body).digest('base64url');if(sig!==expected)return null;const payload=JSON.parse(Buffer.from(body,'base64url').toString());return payload.exp>Date.now()?payload:null;}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>1e6)throw new Error('Payload muito grande');}return raw?JSON.parse(raw):{};}
function auth(req){return verify(req.headers.authorization?.replace(/^Bearer\s+/i,''));}
const authAttempts=new Map();
function authRateLimited(req){const key=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim(),time=Date.now(),windowMs=15*60*1000,limit=20;const recent=(authAttempts.get(key)||[]).filter(t=>time-t<windowMs);recent.push(time);authAttempts.set(key,recent);return recent.length>limit;}
const mapCache=new Map();
let lastGeocodeAt=0;
let geocodeQueue=Promise.resolve();
function clientKey(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim();}
function mapRateLimited(req){const key=`map:${clientKey(req)}`,time=Date.now(),windowMs=15*60*1000,limit=60;const recent=(authAttempts.get(key)||[]).filter(t=>time-t<windowMs);recent.push(time);authAttempts.set(key,recent);return recent.length>limit;}
async function externalJson(target,{geocode=false}={}){const cacheKey=target.toString(),cached=mapCache.get(cacheKey);if(cached&&cached.expires>Date.now())return cached.data;if(geocode){const previous=geocodeQueue;let release;geocodeQueue=new Promise(resolve=>{release=resolve});await previous;const wait=Math.max(0,1000-(Date.now()-lastGeocodeAt));if(wait)await new Promise(resolve=>setTimeout(resolve,wait));lastGeocodeAt=Date.now();release()}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(target,{headers:{'User-Agent':`ViaFacil/2.0 (${MAP_CONTACT_EMAIL||'https://via-facil.onrender.com'})`,'Accept-Language':'pt-BR,pt;q=0.9'},signal:controller.signal});if(!response.ok)throw new Error(`Serviço de mapas respondeu ${response.status}`);const data=await response.json();if(mapCache.size>=500)mapCache.delete(mapCache.keys().next().value);mapCache.set(cacheKey,{data,expires:Date.now()+24*60*60*1000});return data;}finally{clearTimeout(timer)}}
function validCoordinate(value,min,max){const number=Number(value);return Number.isFinite(number)&&number>=min&&number<=max;}
function stopsFor(ride){return Array.isArray(ride.stops)&&ride.stops.length>1?ride.stops:[ride.origin,ride.destination];}
function segmentOnRide(ride,pickup,dropoff){const stops=stopsFor(ride).map(s=>s.toLocaleLowerCase('pt-BR'));const from=stops.indexOf(String(pickup||'').trim().toLocaleLowerCase('pt-BR'));const to=stops.indexOf(String(dropoff||'').trim().toLocaleLowerCase('pt-BR'));return from>=0&&to>from;}

async function seed(){const db=await readDb();if(db.users.length)return;if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD){const pass=hashPassword(process.env.ADMIN_PASSWORD);db.users.push({id:id('usr'),name:process.env.ADMIN_NAME||'Administrador Via Fácil',email:process.env.ADMIN_EMAIL.trim().toLowerCase(),phone:'',role:'admin',rating:5,verified:true,...pass,createdAt:now()});await writeDb(db);return;}if(IS_PRODUCTION)return;const adminId=id('usr'),driverId=id('usr');const a=hashPassword('admin123'),d=hashPassword('motorista123');db.users.push({id:adminId,name:'Administrador Via Fácil',email:'admin@viafacil.com',phone:'(00) 90000-0000',role:'admin',rating:5,verified:true,...a,createdAt:now()},{id:driverId,name:'Carlos Motorista',email:'motorista@viafacil.com',phone:'(00) 98888-0000',role:'driver',rating:4.9,verified:true,vehicle:'Chevrolet Onix • ABC1D23',...d,createdAt:now()});const date=(n)=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);db.rides.push({id:id('ride'),driverId,origin:'Centro',destination:'Aeroporto',date:date(1),time:'08:00',seats:3,availableSeats:3,price:28,vehicle:'Chevrolet Onix',notes:'Uma parada rápida no caminho.',status:'active',createdAt:now()},{id:id('ride'),driverId,origin:'Rodoviária',destination:'Centro',date:date(2),time:'17:30',seats:4,availableSeats:4,price:18,vehicle:'Chevrolet Onix',notes:'Bagagem pequena permitida.',status:'active',createdAt:now()});await writeDb(db);}

async function api(req,res,url){
  const user=auth(req);const db=await readDb();const method=req.method;
  if(method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,app:'Via Fácil',storage:pool?'postgres':'json'});
  if(method==='GET'&&url.pathname==='/api/maps/geocode'){if(mapRateLimited(req))return json(res,429,{error:'Muitas consultas de endereço. Aguarde alguns minutos.'});const query=String(url.searchParams.get('q')||'').trim().slice(0,200);if(query.length<3)return json(res,400,{error:'Digite um endereço com pelo menos 3 caracteres.'});const target=new URL('/search',GEOCODING_URL);target.searchParams.set('q',query);target.searchParams.set('format','jsonv2');target.searchParams.set('limit','5');target.searchParams.set('countrycodes','br');target.searchParams.set('addressdetails','1');if(MAP_CONTACT_EMAIL)target.searchParams.set('email',MAP_CONTACT_EMAIL);const results=await externalJson(target,{geocode:true});return json(res,200,{results:results.map(item=>({label:item.display_name,city:item.address?.city||item.address?.town||item.address?.municipality||item.address?.village||'',state:item.address?.state||'',stateCode:item.address?.['ISO3166-2-lvl4']?.replace('BR-','')||'',lat:Number(item.lat),lon:Number(item.lon),type:item.type})).filter(item=>validCoordinate(item.lat,-90,90)&&validCoordinate(item.lon,-180,180))});}
  if(method==='GET'&&url.pathname==='/api/maps/route'){if(mapRateLimited(req))return json(res,429,{error:'Muitas consultas de rota. Aguarde alguns minutos.'});const points=String(url.searchParams.get('points')||'').split('|').map(point=>point.split(',').map(Number));if(points.length<2||points.length>10||points.some(([lon,lat])=>!validCoordinate(lon,-180,180)||!validCoordinate(lat,-90,90)))return json(res,400,{error:'Informe entre 2 e 10 pontos válidos.'});const target=new URL(`/route/v1/driving/${points.map(point=>point.join(',')).join(';')}`,ROUTING_URL);target.searchParams.set('overview','full');target.searchParams.set('geometries','geojson');target.searchParams.set('steps','false');const data=await externalJson(target);const route=data.routes?.[0];if(!route)return json(res,404,{error:'Não foi possível calcular uma rota por estrada entre esses pontos.'});return json(res,200,{route:{distanceMeters:route.distance,durationSeconds:route.duration,geometry:route.geometry}});}
  if(method==='POST'&&url.pathname==='/api/auth/register'){if(authRateLimited(req))return json(res,429,{error:'Muitas tentativas. Aguarde alguns minutos.'});const data=await body(req),email=String(data.email||'').trim().toLowerCase(),name=String(data.name||'').trim(),password=String(data.password||'');if(!name||!email||!password)return json(res,400,{error:'Nome, e-mail e senha são obrigatórios.'});if(name.length>100||email.length>254||password.length<8||password.length>128)return json(res,400,{error:'Use um nome válido e senha entre 8 e 128 caracteres.'});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json(res,400,{error:'Informe um e-mail válido.'});if(db.users.some(u=>u.email.toLowerCase()===email))return json(res,409,{error:'Este e-mail já está cadastrado.'});const pass=hashPassword(password);const newUser={id:id('usr'),name,email,phone:String(data.phone||'').trim().slice(0,30),role:['passenger','driver'].includes(data.role)?data.role:'passenger',rating:5,verified:false,...pass,createdAt:now()};db.users.push(newUser);await writeDb(db);return json(res,201,{token:sign({id:newUser.id,role:newUser.role,name:newUser.name}),user:cleanUser(newUser)});}
  if(method==='POST'&&url.pathname==='/api/auth/login'){if(authRateLimited(req))return json(res,429,{error:'Muitas tentativas. Aguarde alguns minutos.'});const data=await body(req),email=String(data.email||'').trim().toLowerCase(),password=String(data.password||'');const found=db.users.find(u=>u.email.toLowerCase()===email);if(!found||!verifyPassword(password,found))return json(res,401,{error:'E-mail ou senha incorretos.'});return json(res,200,{token:sign({id:found.id,role:found.role,name:found.name}),user:cleanUser(found)});}
  if(method==='GET'&&url.pathname==='/api/rides'){const origin=url.searchParams.get('origin')||'',destination=url.searchParams.get('destination')||'',date=url.searchParams.get('date')||'';const rides=db.rides.filter(r=>r.status==='active').filter(r=>{if(!origin&&!destination)return true;const stops=stopsFor(r).map(s=>s.toLowerCase());const from=origin?stops.findIndex(s=>s.includes(origin.toLowerCase())):0;const to=destination?stops.findIndex((s,i)=>i>from&&s.includes(destination.toLowerCase())):stops.length-1;return from>=0&&to>from;}).filter(r=>!date||r.date===date).map(r=>({...r,stops:stopsFor(r),acceptsPassengers:r.acceptsPassengers!==false,acceptsDeliveries:r.acceptsDeliveries===true,driver:publicUser(db.users.find(u=>u.id===r.driverId)||{},db.reviews)})).sort((a,b)=>`${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`));return json(res,200,{rides});}
  const driverProfileMatch=url.pathname.match(/^\/api\/drivers\/([^/]+)$/);if(method==='GET'&&driverProfileMatch){const driver=db.users.find(u=>u.id===driverProfileMatch[1]&&['driver','admin'].includes(u.role));if(!driver)return json(res,404,{error:'Perfil do motorista não encontrado.'});const rides=db.rides.filter(ride=>ride.driverId===driver.id&&ride.status==='active').map(ride=>({...ride,stops:stopsFor(ride),acceptsPassengers:ride.acceptsPassengers!==false,acceptsDeliveries:ride.acceptsDeliveries===true})).sort((a,b)=>`${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`)),reviews=db.reviews.filter(review=>review.driverId===driver.id).map(review=>({...review,passenger:{name:db.users.find(person=>person.id===review.passengerId)?.name||'Passageiro'}})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return json(res,200,{driver:publicUser(driver,db.reviews),rides,reviews});}
  if(!user)return json(res,401,{error:'Faça login para continuar.'});
  if(method==='GET'&&url.pathname==='/api/me'){const found=db.users.find(u=>u.id===user.id);return json(res,200,{user:cleanUser(found)});}
  if(method==='GET'&&url.pathname==='/api/my/reviewable-rides'){const driverId=String(url.searchParams.get('driverId')||''),today=new Date().toISOString().slice(0,10),reviewed=new Set(db.reviews.filter(review=>review.passengerId===user.id).map(review=>review.rideId)),rides=db.bookings.filter(booking=>booking.passengerId===user.id&&booking.status==='confirmed'&&!reviewed.has(booking.rideId)).map(booking=>db.rides.find(ride=>ride.id===booking.rideId&&ride.driverId===driverId&&ride.date<=today)).filter(Boolean).map(ride=>({id:ride.id,stops:stopsFor(ride),date:ride.date,time:ride.time}));return json(res,200,{rides});}
  if(method==='PATCH'&&url.pathname==='/api/me/profile'){const found=db.users.find(u=>u.id===user.id);if(!found||!['driver','admin'].includes(found.role))return json(res,403,{error:'Apenas motoristas podem configurar este perfil.'});const data=await body(req),methods=Array.isArray(data.paymentMethods)?data.paymentMethods:[],allowedMethods=['pix','cash','card','payment_link'];let paymentLink=String(data.paymentLink||'').trim(),profilePhoto=String(data.profilePhoto||'').trim();for(const [value,label] of [[paymentLink,'link de pagamento'],[profilePhoto,'endereço da foto']])if(value){let parsed;try{parsed=new URL(value)}catch{return json(res,400,{error:`Informe um ${label} válido.`})}if(parsed.protocol!=='https:')return json(res,400,{error:`O ${label} deve usar HTTPS.`})}found.profileTitle=String(data.profileTitle||found.name).trim().slice(0,80);found.bio=String(data.bio||'').trim().slice(0,500);found.serviceArea=String(data.serviceArea||'').trim().slice(0,160);found.paymentMethods=[...new Set(methods.filter(method=>allowedMethods.includes(method)))];found.paymentLink=paymentLink.slice(0,500);found.profilePhoto=profilePhoto.slice(0,500);found.profileUpdatedAt=now();await writeDb(db);return json(res,200,{user:cleanUser(found)});}
  const reviewMatch=url.pathname.match(/^\/api\/drivers\/([^/]+)\/reviews$/);if(method==='POST'&&reviewMatch){const driver=db.users.find(person=>person.id===reviewMatch[1]&&['driver','admin'].includes(person.role)),data=await body(req),ride=db.rides.find(item=>item.id===data.rideId&&item.driverId===driver?.id),booking=ride&&db.bookings.find(item=>item.rideId===ride.id&&item.passengerId===user.id&&item.status==='confirmed'),rating=Number(data.rating),comment=String(data.comment||'').trim();if(!driver||!ride||!booking)return json(res,403,{error:'Somente passageiros com reserva confirmada podem avaliar este motorista.'});if(ride.date>new Date().toISOString().slice(0,10))return json(res,400,{error:'A avaliação ficará disponível após a data da viagem.'});if(db.reviews.some(review=>review.rideId===ride.id&&review.passengerId===user.id))return json(res,409,{error:'Você já avaliou esta viagem.'});if(!Number.isInteger(rating)||rating<1||rating>5)return json(res,400,{error:'Escolha uma nota de 1 a 5.'});const review={id:id('review'),driverId:driver.id,rideId:ride.id,bookingId:booking.id,passengerId:user.id,rating,comment:comment.slice(0,500),createdAt:now()};db.reviews.push(review);await writeDb(db);return json(res,201,{review});}
  if(method==='POST'&&url.pathname==='/api/rides'){const data=await body(req);const stops=[data.origin,...(Array.isArray(data.intermediateStops)?data.intermediateStops:[]),data.destination].map(s=>String(s||'').trim()).filter(Boolean);if(stops.length<2||!data.date||!data.time||!data.seats||data.price===undefined)return json(res,400,{error:'Preencha todos os campos obrigatórios.'});if(new Set(stops.map(s=>s.toLowerCase())).size!==stops.length)return json(res,400,{error:'Cada parada do percurso deve ser diferente.'});const routePoints=Array.isArray(data.routePoints)?data.routePoints.slice(0,10).map(point=>({label:String(point.label||'').slice(0,200),lat:Number(point.lat),lon:Number(point.lon)})).filter(point=>validCoordinate(point.lat,-90,90)&&validCoordinate(point.lon,-180,180)):[];const routeSummary=data.routeSummary&&routePoints.length===stops.length?{distanceMeters:Number(data.routeSummary.distanceMeters)||0,durationSeconds:Number(data.routeSummary.durationSeconds)||0}:null;const ride={id:id('ride'),driverId:user.id,origin:stops[0],destination:stops.at(-1),stops,routePoints,routeSummary,date:data.date,time:data.time,seats:Number(data.seats),availableSeats:Number(data.seats),price:Number(data.price),deliveryPrice:Number(data.deliveryPrice||0),acceptsPassengers:data.acceptsPassengers!==false,acceptsDeliveries:data.acceptsDeliveries===true,vehicle:data.vehicle||'Veículo não informado',notes:data.notes||'',status:'active',createdAt:now()};if(!ride.acceptsPassengers&&!ride.acceptsDeliveries)return json(res,400,{error:'Selecione passageiros, entregas ou ambos.'});db.rides.push(ride);await writeDb(db);return json(res,201,{ride});}
  const bookMatch=url.pathname.match(/^\/api\/rides\/([^/]+)\/book$/);if(method==='POST'&&bookMatch){const data=await body(req),seats=Number(data.seats||1),ride=db.rides.find(r=>r.id===bookMatch[1]);if(!ride||ride.status!=='active')return json(res,404,{error:'Carona não encontrada.'});if(ride.acceptsPassengers===false)return json(res,400,{error:'Este percurso aceita somente entregas.'});if(ride.driverId===user.id)return json(res,400,{error:'Você não pode reservar sua própria carona.'});if(!segmentOnRide(ride,data.pickup,data.dropoff))return json(res,400,{error:'Selecione um trecho válido na ordem do percurso.'});if(seats<1||seats>ride.availableSeats)return json(res,400,{error:'Quantidade de vagas indisponível.'});const booking={id:id('book'),rideId:ride.id,passengerId:user.id,pickup:data.pickup,dropoff:data.dropoff,seats,total:seats*ride.price,status:'pending',createdAt:now()};db.bookings.push(booking);await writeDb(db);return json(res,201,{booking});}
  if(method==='GET'&&url.pathname==='/api/my/bookings')return json(res,200,{bookings:db.bookings.filter(b=>b.passengerId===user.id).map(b=>({...b,ride:db.rides.find(r=>r.id===b.rideId)}))});
  if(method==='GET'&&url.pathname==='/api/my/ride-requests')return json(res,200,{bookings:db.bookings.filter(b=>db.rides.find(r=>r.id===b.rideId)?.driverId===user.id).map(b=>({...b,ride:db.rides.find(r=>r.id===b.rideId),passenger:cleanUser(db.users.find(u=>u.id===b.passengerId)||{})}))});
  const respondMatch=url.pathname.match(/^\/api\/bookings\/([^/]+)\/respond$/);if(method==='PATCH'&&respondMatch){const data=await body(req),booking=db.bookings.find(b=>b.id===respondMatch[1]),ride=booking&&db.rides.find(r=>r.id===booking.rideId);if(!booking||!ride||ride.driverId!==user.id)return json(res,404,{error:'Solicitação não encontrada.'});if(booking.status!=='pending')return json(res,400,{error:'Esta solicitação já foi respondida.'});if(data.action==='accept'){if(booking.seats>ride.availableSeats)return json(res,400,{error:'Não há mais vagas suficientes.'});booking.status='confirmed';ride.availableSeats-=booking.seats;}else if(data.action==='reject')booking.status='rejected';else return json(res,400,{error:'Ação inválida.'});booking.respondedAt=now();await writeDb(db);return json(res,200,{booking});}
  const cancelMatch=url.pathname.match(/^\/api\/bookings\/([^/]+)\/cancel$/);if(method==='PATCH'&&cancelMatch){const booking=db.bookings.find(b=>b.id===cancelMatch[1]&&b.passengerId===user.id);if(!booking)return json(res,404,{error:'Reserva não encontrada.'});if(!['cancelled','rejected'].includes(booking.status)){const wasConfirmed=booking.status==='confirmed';booking.status='cancelled';const ride=db.rides.find(r=>r.id===booking.rideId);if(ride&&wasConfirmed)ride.availableSeats+=booking.seats;await writeDb(db);}return json(res,200,{booking});}
  if(method==='POST'&&url.pathname==='/api/deliveries'){const data=await body(req),ride=db.rides.find(r=>r.id===data.rideId);if(!ride||ride.status!=='active'||ride.acceptsDeliveries!==true)return json(res,400,{error:'Selecione um percurso que aceite entregas.'});if(ride.driverId===user.id)return json(res,400,{error:'Você não pode solicitar entrega na própria viagem.'});if(!segmentOnRide(ride,data.pickup,data.destination))return json(res,400,{error:'A coleta e a entrega precisam seguir a ordem do percurso.'});if(!data.packageType||!data.recipient)return json(res,400,{error:'Preencha todos os campos obrigatórios.'});const delivery={id:id('del'),rideId:ride.id,customerId:user.id,pickup:data.pickup,destination:data.destination,date:ride.date,time:ride.time,packageType:data.packageType,recipient:data.recipient,phone:data.phone||'',notes:data.notes||'',status:'requested',trackingCode:`VF${Math.random().toString(36).slice(2,8).toUpperCase()}`,createdAt:now()};db.deliveries.push(delivery);await writeDb(db);return json(res,201,{delivery});}
  if(method==='GET'&&url.pathname==='/api/my/deliveries')return json(res,200,{deliveries:db.deliveries.filter(d=>d.customerId===user.id)});
  const messageMatch=url.pathname.match(/^\/api\/rides\/([^/]+)\/messages$/);if(messageMatch&&(method==='GET'||method==='POST')){const ride=db.rides.find(r=>r.id===messageMatch[1]);if(!ride)return json(res,404,{error:'Carona não encontrada.'});const data=method==='POST'?await body(req):{};const participantId=ride.driverId===user.id?(url.searchParams.get('participantId')||data.recipientId):user.id;if(!participantId)return json(res,400,{error:'Informe o passageiro da conversa.'});if(method==='GET'){const messages=db.messages.filter(m=>m.rideId===ride.id&&m.participantId===participantId);return json(res,200,{messages,ride:{...ride,stops:stopsFor(ride)},participant:cleanUser(db.users.find(u=>u.id===participantId)||{})});}if(!String(data.text||'').trim())return json(res,400,{error:'Digite uma mensagem.'});const message={id:id('msg'),rideId:ride.id,participantId,senderId:user.id,text:String(data.text).trim().slice(0,1000),createdAt:now()};db.messages.push(message);await writeDb(db);return json(res,201,{message});}
  if(method==='GET'&&url.pathname==='/api/my/conversations'){const mine=db.messages.filter(m=>m.senderId===user.id||m.participantId===user.id);const keys=[...new Set(mine.map(m=>`${m.rideId}|${m.participantId}`))];const conversations=keys.map(key=>{const [rideId,participantId]=key.split('|'),items=mine.filter(m=>m.rideId===rideId&&m.participantId===participantId);return {ride:db.rides.find(r=>r.id===rideId),participant:cleanUser(db.users.find(u=>u.id===participantId)||{}),lastMessage:items.at(-1)};}).filter(c=>c.ride).sort((a,b)=>b.lastMessage.createdAt.localeCompare(a.lastMessage.createdAt));return json(res,200,{conversations});}
  if(method==='GET'&&url.pathname==='/api/admin/summary'){if(user.role!=='admin')return json(res,403,{error:'Acesso restrito ao administrador.'});return json(res,200,{users:db.users.length,rides:db.rides.length,bookings:db.bookings.length,deliveries:db.deliveries.length,revenue:db.bookings.filter(b=>b.status==='confirmed').reduce((s,b)=>s+b.total,0)});}
  return json(res,404,{error:'Rota não encontrada.'});
}

async function serve(req,res,url){let pathname=decodeURIComponent(url.pathname);if(pathname==='/')pathname='/index.html';const vendorFiles={'/vendor/leaflet.css':'leaflet.css','/vendor/leaflet.js':'leaflet.js','/vendor/images/marker-icon.png':'images/marker-icon.png','/vendor/images/marker-icon-2x.png':'images/marker-icon-2x.png','/vendor/images/marker-shadow.png':'images/marker-shadow.png'};let root=PUBLIC_DIR,relative=pathname;if(vendorFiles[pathname]){root=LEAFLET_DIR;relative=vendorFiles[pathname]}let file=path.normalize(path.join(root,relative));if(!file.startsWith(root))return json(res,403,{error:'Acesso negado.'});try{const data=await fs.readFile(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':vendorFiles[pathname]?'public, max-age=31536000, immutable':'no-cache'});res.end(data);}catch{const data=await fs.readFile(path.join(PUBLIC_DIR,'index.html'));res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(data);}}

await seed();
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'self'; connect-src 'self' https://*.tile.openstreetmap.org");try{const url=new URL(req.url,`http://${req.headers.host||'127.0.0.1'}`);if(url.pathname.startsWith('/api/'))await api(req,res,url);else await serve(req,res,url);}catch(err){console.error(err);json(res,err.name==='AbortError'?504:500,{error:err.name==='AbortError'?'O serviço de mapas demorou para responder.':'Erro interno do servidor.'});}});
server.listen(PORT, '0.0.0.0', () => {
  console.log(`\nVIA FÁCIL disponível na porta ${PORT}\n`);
});
